const PDFDocument = require("pdfkit");
const fs = require("fs");
const path = require("path");

const generateInvoiceReceipt = (invoice) => {
    return new Promise((resolve, reject) => {
        try {
            const receiptsDir = path.join(
                __dirname,
                "../receipts"
            );

            // Create receipts folder if it doesn't exist
            if (!fs.existsSync(receiptsDir)) {
                fs.mkdirSync(receiptsDir, {
                    recursive: true
                });
            }

            const fileName =
                `${invoice.invoiceNumber}-receipt.pdf`;

            const filePath = path.join(
                receiptsDir,
                fileName
            );

            const doc = new PDFDocument({
                size: "A4",
                margin: 50
            });

            const stream = fs.createWriteStream(filePath);

            doc.pipe(stream);

            // =========================================
            // HEADER
            // =========================================

            doc
                .fontSize(24)
                .font("Helvetica-Bold")
                .text("NEXUS CORPORATE SERVICES", {
                    align: "center"
                });

            doc
                .moveDown(0.5)
                .fontSize(18)
                .font("Helvetica")
                .text("PAYMENT RECEIPT", {
                    align: "center"
                });

            doc.moveDown(1);

            // =========================================
            // PAID STAMP
            // =========================================

            doc
                .fontSize(28)
                .font("Helvetica-Bold")
                .text("PAID", {
                    align: "center"
                });

            doc.moveDown(1);

            // =========================================
            // INVOICE INFORMATION
            // =========================================

            doc
                .fontSize(12)
                .font("Helvetica-Bold")
                .text("Invoice Information");

            doc.moveDown(0.5);

            doc
                .fontSize(11)
                .font("Helvetica")
                .text(
                    `Invoice Number: ${invoice.invoiceNumber}`
                )
                .text(
                    `Client Name: ${invoice.clientName}`
                )
                .text(
                    `Client Email: ${invoice.clientEmail}`
                )
                .text(
                    `Description: ${invoice.description}`
                );

            doc.moveDown(1);

            // =========================================
            // PAYMENT DETAILS
            // =========================================

            doc
                .fontSize(12)
                .font("Helvetica-Bold")
                .text("Payment Details");

            doc.moveDown(0.5);

            const formattedAmount =
                new Intl.NumberFormat("en-US", {
                    style: "currency",
                    currency:
                        invoice.currency?.toUpperCase() ||
                        "USD"
                }).format(invoice.amount);

            const paidDate = invoice.paidAt
                ? new Date(
                      invoice.paidAt
                  ).toLocaleDateString("en-US", {
                      year: "numeric",
                      month: "long",
                      day: "numeric"
                  })
                : "-";

            doc
                .fontSize(11)
                .font("Helvetica")
                .text(
                    `Amount Paid: ${formattedAmount}`
                )
                .text(
                    `Payment Date: ${paidDate}`
                )
                .text(
                    `Payment Status: PAID`
                );

            if (invoice.stripePaymentIntentId) {
                doc.text(
                    `Stripe Payment ID: ${invoice.stripePaymentIntentId}`
                );
            }

            doc.moveDown(2);

            // =========================================
            // FOOTER
            // =========================================

            doc
                .fontSize(10)
                .font("Helvetica")
                .text(
                    "Thank you for your payment.",
                    {
                        align: "center"
                    }
                );

            doc
                .moveDown(0.5)
                .text(
                    "This receipt was automatically generated by VaultPay.",
                    {
                        align: "center"
                    }
                );

            doc.end();

            stream.on("finish", () => {
                resolve(filePath);
            });

            stream.on("error", (error) => {
                reject(error);
            });

        } catch (error) {
            reject(error);
        }
    });
};

module.exports = {
    generateInvoiceReceipt
};